/**
 * Restore Database Script for NexiaMind AI
 *
 * This script restores a Supabase database from a backup generated by
 * backup-db.js, executing the SQL for real through the REST API
 * (SUPABASE_URL + SUPABASE_SERVICE_ROLE_KEY) via the `exec_sql_batch` RPC
 * function — no direct PostgreSQL connection required.
 *
 * Usage: node scripts/database/restore-db.js --file=backup-nexiamind-2026-07-15-12-00-00.sql
 *
 * Environment Variables Required:
 *   SUPABASE_URL: Supabase project URL
 *   SUPABASE_SERVICE_ROLE_KEY: Service role key with full access
 *
 * Prerequisite: run scripts/database/setup-exec-sql-functions.sql ONCE in the
 * Supabase SQL Editor (same prerequisite as backup-db.js).
 *
 * Options:
 *   --file, -f: Path to the .sql backup file (either a bare filename resolved
 *     against scripts/database/backups/, or an absolute path ending in .sql).
 *     The sibling .json file (same basename) is read for actual execution —
 *     it holds the statements as a plain array, avoiding any need to re-parse
 *     the human-readable .sql text (which can contain embedded semicolons/
 *     newlines inside string literals that a hand-rolled parser gets wrong).
 *   --drop, -d: Drop existing tables before restore (default: false)
 *   --yes, -y: Skip confirmation prompt
 *
 * Both --file=value and space-separated --file value forms are supported.
 */

const { createClient } = require('@supabase/supabase-js');
const fs = require('fs');
const path = require('path');
const readline = require('readline');
const dotenv = require('dotenv');

dotenv.config();

const SUPABASE_URL = process.env.SUPABASE_URL;
const SUPABASE_SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;

if (!SUPABASE_URL || !SUPABASE_SERVICE_ROLE_KEY) {
  console.error('Error: SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY environment variables are required');
  process.exit(1);
}

const TABLES = ['profiles', 'documents', 'chunks', 'embeddings', 'conversations', 'messages', 'sync_logs'];

/**
 * Parse command line arguments, supporting both `--flag=value` and
 * space-separated `--flag value` forms, plus boolean-only flags (`--yes`).
 */
function parseArgs(argv) {
  const flagsWithValue = new Set(['file', 'f']);
  const args = {};

  for (let i = 0; i < argv.length; i++) {
    const token = argv[i];
    if (!token.startsWith('-')) continue;

    const key = token.replace(/^--?/, '');
    const eqIndex = key.indexOf('=');

    if (eqIndex !== -1) {
      args[key.slice(0, eqIndex)] = key.slice(eqIndex + 1);
      continue;
    }

    const next = argv[i + 1];
    if (flagsWithValue.has(key) && next !== undefined && !next.startsWith('-')) {
      args[key] = next;
      i++;
    } else {
      args[key] = true;
    }
  }

  return args;
}

/**
 * Interpret a parsed flag value as a boolean, so `--drop=false` disables the
 * flag instead of being treated as a truthy non-empty string.
 */
function asBoolean(value) {
  if (typeof value === 'boolean') return value;
  if (typeof value === 'string') return value.toLowerCase() !== 'false' && value !== '0';
  return false;
}

const args = parseArgs(process.argv.slice(2));

if (!args.file && !args.f) {
  console.error('Error: --file or -f argument is required');
  console.error('Usage: node restore-db.js --file backup-nexiamind-YYYY-MM-DD-HH-MM-SS.sql');
  process.exit(1);
}

const backupFileArg = args.file || args.f;
const dropExisting = asBoolean(args.drop || args.d);
const skipPrompt = asBoolean(args.yes || args.y);

if (typeof backupFileArg !== 'string') {
  console.error('Error: --file requires a filename value');
  process.exit(1);
}

const backupsDir = path.join(__dirname, 'backups');

/**
 * Resolve the backup file path, containing it to the backups/ directory
 * unless an absolute .sql path is explicitly given (still validated to
 * actually be a .sql file, to avoid accidentally reading arbitrary files
 * like .env via a typo'd relative path with `..` segments).
 */
function resolveBackupPath(fileArg) {
  if (path.isAbsolute(fileArg)) {
    if (path.extname(fileArg).toLowerCase() !== '.sql') {
      throw new Error(`Refusing to read non-.sql file: ${fileArg}`);
    }
    return fileArg;
  }

  const resolved = path.resolve(backupsDir, fileArg);
  if (path.relative(backupsDir, resolved).startsWith('..')) {
    throw new Error(`Refusing to read a path outside ${backupsDir}: ${fileArg}`);
  }
  return resolved;
}

let sqlPath;
try {
  sqlPath = resolveBackupPath(backupFileArg);
} catch (err) {
  console.error(`Error: ${err.message}`);
  process.exit(1);
}

if (!fs.existsSync(sqlPath)) {
  console.error(`Error: Backup file not found: ${sqlPath}`);
  console.error(`Available backups in ${backupsDir}:`);
  if (fs.existsSync(backupsDir)) {
    fs.readdirSync(backupsDir).forEach((file) => console.error(`  - ${file}`));
  }
  process.exit(1);
}

const jsonPath = sqlPath.replace(/\.sql$/i, '.json');

let supabase;
try {
  supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY);
} catch (err) {
  console.error(`Error: Invalid Supabase configuration — ${err.message}`);
  process.exit(1);
}

/**
 * Execute a batch of statements in one RPC call (one transaction) via the
 * exec_sql_batch function.
 */
async function execBatch(statements) {
  const { error } = await supabase.rpc('exec_sql_batch', { queries: statements });
  if (error) {
    throw new Error(
      `exec_sql_batch a échoué: ${error.message}\n`
      + `Avez-vous exécuté scripts/database/setup-exec-sql-functions.sql sur ce projet Supabase ?`
    );
  }
}

async function execQuery(sql) {
  const { data, error } = await supabase.rpc('exec_sql_query', { query: sql });
  if (error) {
    throw new Error(`exec_sql_query a échoué: ${error.message}\nQuery: ${sql}`);
  }
  return data || [];
}

/**
 * Load the statements to execute. Prefers the machine-readable .json file
 * written alongside the .sql by backup-db.js (exact statement array, no
 * parsing needed). Falls back to a best-effort split of the .sql file if
 * the .json sibling is missing, with a clear warning — this fallback can
 * misbehave on data containing embedded semicolons/newlines.
 */
function loadStatements() {
  if (fs.existsSync(jsonPath)) {
    return JSON.parse(fs.readFileSync(jsonPath, 'utf8'));
  }

  console.log(`\n⚠️  Fichier ${path.basename(jsonPath)} introuvable — repli sur un découpage approximatif du .sql.`);
  console.log('   Ce mode dégradé peut mal se comporter si des données contiennent des points-virgules ou des retours à la ligne.');

  const content = fs.readFileSync(sqlPath, 'utf8');
  return content
    .split('\n')
    .filter((line) => !line.trim().startsWith('--'))
    .join('\n')
    .split(';\n')
    .map((s) => s.trim())
    .filter(Boolean);
}

/**
 * Count INSERT statements per table, to sanity-check against post-restore
 * row counts.
 */
function countExpectedRows(statements, tables) {
  const counts = {};
  for (const table of tables) {
    const re = new RegExp(`^INSERT INTO public\\."?${table}"?\\b`, 'i');
    counts[table] = statements.filter((s) => re.test(s)).length;
  }
  return counts;
}

function dropTableStatements() {
  return [...TABLES].reverse().map((table) => `DROP TABLE IF EXISTS public."${table}" CASCADE`);
}

/**
 * Verify backup file structure before attempting restore.
 */
function verifyBackupFile() {
  const content = fs.readFileSync(sqlPath, 'utf8');

  const hasCreateTable = content.includes('CREATE TABLE');
  const hasInsert = content.includes('INSERT INTO');
  const hasIndexes = content.includes('CREATE INDEX');

  console.log('\nVerifying backup file...');
  console.log(`  ✓ CREATE TABLE statements: ${hasCreateTable ? 'Yes' : 'No'}`);
  console.log(`  ✓ INSERT statements: ${hasInsert ? 'Yes' : 'No'}`);
  console.log(`  ✓ Index definitions: ${hasIndexes ? 'Yes' : 'No'}`);
  console.log(`  ✓ Machine-readable .json sibling: ${fs.existsSync(jsonPath) ? 'Yes' : 'No (fallback parsing will be used)'}`);

  const foundTables = TABLES.filter((t) => content.includes(`public.${t}`) || content.includes(`public."${t}"`));
  console.log(`  ✓ Tables found: ${foundTables.length}/${TABLES.length}`);
  foundTables.forEach((t) => console.log(`    - ${t}`));

  const missingTables = TABLES.filter((t) => !foundTables.includes(t));
  if (missingTables.length > 0) {
    console.log(`  ⚠️  Missing tables: ${missingTables.join(', ')}`);
  }

  return {
    valid: hasCreateTable && hasInsert,
    fileSize: fs.statSync(sqlPath).size,
    tableCount: foundTables.length,
  };
}

async function confirmRestore() {
  return new Promise((resolve) => {
    if (skipPrompt) {
      resolve(true);
      return;
    }

    const rl = readline.createInterface({ input: process.stdin, output: process.stdout });

    console.log('\n⚠️  WARNING: This will RESTORE the database from backup!');
    console.log('    Existing data may be overwritten.');
    console.log('\nAre you sure you want to continue? (yes/no):');

    rl.question('> ', (answer) => {
      rl.close();
      const normalized = answer.trim().toLowerCase();
      resolve(normalized === 'yes' || normalized === 'y');
    });
  });
}

/**
 * Verify that restore was successful by comparing actual row counts against
 * the number of INSERT statements found in the backup.
 */
async function verifyRestore(expectedCounts) {
  console.log('\nVerifying restore...');

  let allMatch = true;

  for (const table of TABLES) {
    try {
      const rows = await execQuery(`select count(*) as count from public."${table}"`);
      const actual = Number(rows[0]?.count ?? 0);
      const expected = expectedCounts[table] ?? 0;
      const match = actual === expected;
      allMatch = allMatch && match;
      console.log(`  ${match ? '✓' : '⚠️ '} ${table}: ${actual} rows (attendu: ${expected})`);
    } catch (err) {
      allMatch = false;
      console.log(`  ❌ ${table}: Error - ${err.message}`);
    }
  }

  console.log(allMatch ? '\n✅ Verification complete: all row counts match!' : '\n⚠️  Verification complete with mismatches — see above.');
  return allMatch;
}

async function restoreDatabase() {
  console.log('Starting database restore...\n');
  console.log(`Backup file: ${sqlPath}`);

  const verification = verifyBackupFile();

  if (!verification.valid) {
    console.error('\n❌ Backup file verification failed!');
    console.error('The backup file does not appear to be valid.');
    process.exit(1);
  }

  console.log(`\nBackup file is valid.`);
  console.log(`  Size: ${(verification.fileSize / (1024 * 1024)).toFixed(2)} MB`);
  console.log(`  Tables: ${verification.tableCount}`);

  const confirmed = await confirmRestore();
  if (!confirmed) {
    console.log('\nRestore cancelled.');
    process.exit(0);
  }

  const statements = loadStatements();
  const expectedCounts = countExpectedRows(statements, TABLES);

  const batch = dropExisting ? [...dropTableStatements(), ...statements] : statements;

  console.log(`\nStarting restore (${batch.length} statements, single transaction)...`);
  await execBatch(batch);
  console.log('\n✅ Restore completed successfully!');

  console.log('\nNext steps:');
  console.log('  1. Verify the restored data in your database');
  console.log('  2. Test application functionality');
  console.log('  3. Check indexes are properly restored');

  await verifyRestore(expectedCounts);
}

console.log('='.repeat(60));
console.log('NexiaMind AI Database Restore Script');
console.log('='.repeat(60));

restoreDatabase()
  .then(() => process.exit(0))
  .catch((err) => {
    console.error('\n❌ Restore failed:', err.message);
    process.exit(1);
  });
